
## Generating Random Numbers

Functions for probability distributions in R
- `rnorm`: generate random Normal variates with a given mean and standard deviation
- `dnorm`: evaluate the Normal probability density (with a given mean/SD) at a point (or vector of points)
- `pnorm`: evaluate the cumulative distribution function for a Normal distribution 
- `rpois`: generate random Poisson variates with a given rate


Probability distribution functions usually have four functions associated with them. The functions are prefixed with a
- `d` for density
- `r` for random number generation 
- `p` for cumulative distribution
- `q` for quantile function


Working with the Normal distributions requires using these four functions

```r
x <- rnorm(10) 
dnorm(x, mean = 0, sd = 1, log = FALSE)
pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
rnorm(n, mean = 0, sd = 1)
```

If $\Phi$ is the cumulative distribution function for a standard
Normal distribution, then `pnorm(q)` = $\Phi(q)$ and `qnorm(p)` =
$Φ^{−1}(p)$.


```r
x <- rnorm(10) 
x

x <- rnorm(10, 20, 2) 
x

summary(x)
```


## Setting seed

Setting the random number seed with `set.seed` ensures reproducibility. Always set the random number seed when conducting a simulation!

```r
set.seed(1)
rnorm(5)
rnorm(5)

set.seed(1)
rnorm(5)

```


## Generating Poisson data

```r
rpois(10, 1)
rpois(10, 2)
rpois(10, 20)

## Cumulative distribution - proba that a number in the Poisson distrib of rate 2 is <= 2/4/6
ppois(2, 2)  
ppois(4, 2)
ppois(6, 2)
```


## Generating Random Numbers From a Linear Model

Suppose we want to simulate from the following linear model
\[
y = \beta_0 + \beta_1 x + \varepsilon
\]

where  $\varepsilon\sim\mathcal{N}(0, 2^2)$. 
Assume $x\sim\mathcal{N}(0,1^2)$, $\beta_0 = 0.5$ and $\beta_1 = 2$.

```r

# always set your seed !
set.seed(20)

# Simulate predictor variable (normal distribution)
x <- rnorm(100)
plot (sort(x))

# Simulate the error term (normal distribution)
e <- rnorm(100, 0, 2)
plot (sort(e))

# Compute the outcome via the model 
y <- 0.5 + 2 * x + e

summary(y)

plot(x, y)

```

## Generating Random Numbers From a Linear Model - binary x

```r
set.seed(10)
x <- rbinom(100, 1, 0.5)
e <- rnorm(100, 0, 2)
y <- 0.5 + 2 * x + e
summary(y)
plot(x, y)
```


## Generating Random Numbers From a Generalized Linear Model

Suppose we want to simulate from a Poisson model where

Y ~ Poisson(μ)

log μ = $\beta_0 + \beta_1x$

and $\beta_0 = 0.5$ and $\beta_1 = 0.3$. We need to use the `rpois` function for this

```r
set.seed(1)
x <- rnorm(100)
log.mu <- 0.5 + 0.3 * x
y <- rpois(100, exp(log.mu))
summary(y)
plot(x, y)
```

## Random Sampling

The `sample` function draws randomly from a specified set of (scalar) objects allowing you to sample from arbitrary distributions.

```r
set.seed(1)
sample(1:10, 4)
sample(1:10, 4)
sample(letters, 5)
sample(1:10)  ## permutation
sample(1:10)
sample(1:10, replace = TRUE)  ## Sample w/replacement
```

## Random Data Frame Sampling

```r
library(datasets)
data(airquality)
head(airquality)

set.seed(20)

# Create index vector
idx <- seq_len(nrow(airquality))
idx

# Sample from the index vector
samp <- sample(idx, 6)

airquality[samp, ]
```

---

## Simulation

Summary
- Drawing samples from specific probability distributions can be done with `r*` functions
- Standard distributions are built in: Normal, Poisson, Binomial, Exponential, Gamma, etc.
- The `sample` function can be used to draw random samples from arbitrary vectors
- Setting the random number generator seed via set.seed is critical for reproducibility
