
## Debugging Tools in R

The primary tools for debugging functions in R are
- `traceback`: prints out the function call stack after an error occurs; does nothing if there’s no error
- `debug`: flags a function for “debug” mode which allows you to step through execution of a function one line at a time
- `browser`: suspends the execution of a function wherever it is called and puts the function in debug mode
- `trace`: allows you to insert debugging code into a function a specific places 
- `recover`: allows you to modify the error behavior so that you can browse the function call stack

These are interactive tools specifically designed to allow you to pick through a function. There’s also the more blunt technique of inserting print/cat statements in the function.

---

## traceback

Must be fired before another function is called.

```r
mean(x)
traceback()

lm(y ~ x)
traceback()
```


## debug
```r
debug(lm)
lm(y ~ x)
undebug(lm)
```

A new prompt will appear: `Browse[2]>` .
 . n executes the current expression and moves to the next expression
 . c continues execution of the function and does not stop until either an error or the function exits
 . Q quits the browser


## recover

With recover() you can tell R that when an error occurs, it should halt execution at the exact point at which the error occurred. 

```r
options(error = recover)
read.csv("nosuchfile")
```
